import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { Toaster } from "react-hot-toast";
import type { Metadata } from "next";
import { Poppins, Playfair_Display } from "next/font/google";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"], // Specify desired weights
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const playfair = Playfair_Display({
  weight: ["400", "500", "600", "700", "800"], // Specify desired weights
  subsets: ["latin"],
  variable: "--font-serif",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${playfair.variable}`}>
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="antialiased min-h-screen flex flex-col">
        <Header />
        <main className="flex-grow">
          <Toaster position="top-right" />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
